export const PHYLO_GRAPH_NODE_RADIUS = 4
export const PHYLO_GRAPH_NODE_SPACING_HORIZONTAL = PHYLO_GRAPH_NODE_RADIUS * 2 + 50
export const PHYLO_GRAPH_NODE_SPACING_VERTICAL = PHYLO_GRAPH_NODE_RADIUS * 2 + 5
export const PHYLO_GRAPH_NODE_LABEL_FONT_SIZE = 10
